#ifndef _HS_INI_H_
#define _HS_INI_H_

/* CF: Configure Field */
typedef enum {
	CF_APP_PROBE_NUM,
	CF_CONTENT_SCAN_PACKET_NUM,
	CF_CONTENT_SCAN_DATA_LEN,
	CF_DFI_MAX_SCAN_NUM,
	CF_DFI_AVER_LEN_SCAN_NUM,
	CF_DFI_RADIO_SCAN_NUM,
	CF_HOST_PROBE_NUM,
	CF_TYPICAL_MIN_P2P_LOAD,
	CF_TYPICAL_MIN_P2P_PORT,
	CF_PBDL_MAX_EVENT_NUM,
	CF_MAX_INNER_IP_NUM,
	CF_UNKNOWN,
	CF_MAX = CF_UNKNOWN
} HS_CONF_FIELD_E;

INT32 HS_LoadIni(const CHAR *pcConFile);

#endif
